Repository final-project-teamB/ParkNav2, pull requests merged in 2023-04, with the labels that each got.

#124 feat : #123 입차 예약, 일반 구획수 반반나누기
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/dto/BookingInfoResponseDto.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/dto/NomalBookingCarSpaceInfo.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement

#150 Feat : #149 입차 메서드 테스트 코드 작성
  build.gradle
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#156 Feat: #155 구역을 나타낼 ZONE 필드 추가
  src/main/java/com/sparta/parknav/management/entity/ParkMgtInfo.java
  src/main/java/com/sparta/parknav/management/entity/ZoneType.java
Labels: enhancement

#158 Feat: #157 주차장 검색 부분 FULLTEXT index 적용
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: enhancement

#161 Fix : 4-2 로직 위치 변경
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#163 feat : #162 v2 입차 관련 로직 수정
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#165 Feat : #164 스케쥴러 추가
  src/main/java/com/sparta/parknav/ParknavApplication.java
  src/main/java/com/sparta/parknav/_global/scheduler/SchedulerService.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
Labels: enhancement

#166 Feat: #152 출차 v2 구현
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepository.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepositoryCustom.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepositoryImpl.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#168 fix : v2 출차시 예약 종료시간을 현재 시간으로 변경
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#169 feat : v1 출차시 예약 종료시간을 현재 시간으로 변경
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#170 Feat: #152 예약 취소시 주차가능대수 업데이트
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
Labels: enhancement

#171 Refactor: #152 예약불가 시간대 구하는 로직 리팩토링
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
Labels: refactor

#175 feat : #173 v2 트랜잭션 핸들러 추가
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/_global/handler/TransactionHandler.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/redis/RedisConfig.java
  src/main/java/com/sparta/parknav/redis/RedisLockRepository.java
Labels: enhancement

#177 Refactor: version2 리팩토링
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/dto/NomalBookingCarSpaceInfo.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: refactor

#176 feat : #174 v2 입차, 예약 테스트코드
  src/main/java/com/sparta/parknav/_global/exception/CustomException.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/user/entity/Admin.java
  src/test/java/com/sparta/parknav/booking/service/BookingServiceTest.java
  src/test/java/com/sparta/parknav/management/service/MgtServiceTest.java
Labels: enhancement

#180 Merge : Version2 -> develop 브랜치 머지
  .github/workflows/gradle.yml
  build.gradle
  src/main/java/com/sparta/parknav/ParknavApplication.java
  src/main/java/com/sparta/parknav/_global/exception/CustomException.java
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/_global/handler/TransactionHandler.java
  src/main/java/com/sparta/parknav/_global/redis/RedisConfig.java
  src/main/java/com/sparta/parknav/_global/redis/RedisLockRepository.java
  src/main/java/com/sparta/parknav/_global/scheduler/SchedulerService.java
  src/main/java/com/sparta/parknav/booking/dto/BookingInfoRequestDto.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingByHour.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepository.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepositoryCustom.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepositoryImpl.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/dto/NomalBookingCarSpaceInfo.java
  src/main/java/com/sparta/parknav/management/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtListResponseDto.java
  src/main/java/com/sparta/parknav/management/entity/ParkMgtInfo.java
  src/main/java/com/sparta/parknav/management/entity/ZoneType.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/entity/ParkInfo.java
  src/main/java/com/sparta/parknav/redis/RedisLockRepository.java
  src/main/java/com/sparta/parknav/user/entity/Admin.java
  src/main/java/com/sparta/parknav/user/service/UserService.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/mypage.html
  src/test/java/com/sparta/parknav/booking/service/BookingServiceTest.java
  src/test/java/com/sparta/parknav/management/service/MgtServiceTest.java
Labels: fix

#183 Feat : 입차 불가능 시간대 문구 변경
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
Labels: enhancement

#185 feat : 예약 시작시간과 종료시간의 최대 차이는 1주일로 변경
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/resources/static/js/main.js
Labels: enhancement

#186 fix : #182 관리자페이지 예상출차시간
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#189 Fix : 출차시 요금계산 로직 수정
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#192 Fix : #190 연속 예약 가능하도록 로직 수정
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
Labels: fix

#193 Fix : #191 available 주차가능대수가 총 구획 수를 넘지 않도록 설정
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepositoryImpl.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement, fix

#196 Feat : #195 5th mentoring
  src/main/java/com/sparta/parknav/_global/scheduler/SchedulerService.java
  src/main/java/com/sparta/parknav/booking/dto/MyBookingResponseDto.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/mypage.html
Labels: enhancement, fix

#198 Feat: #194 주차 요금 계산 로직 수정
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/management/service/ParkingFeeCalculator.java
Labels: enhancement

#199 Feat : #197 메인 페이지에서 예약시 대표차량 선택 가능
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement, fix

#202 Fix : 스케쥴링시 예약 테이블의 예약 종료시간이 아니라 exitTime을 보고 park_booking_by_hour변경
  src/main/java/com/sparta/parknav/_global/scheduler/SchedulerService.java
Labels: bug, fix

#204 Feat : 금액 표시 및 출차 안하는 차량 표시
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtListResponseDto.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
Labels: enhancement, fix

#205 feat : #201 예약현황 대시보드 구현
  src/main/java/com/sparta/parknav/_global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingByHourRepository.java
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkAvailableDto.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkAvailableResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/controller/ParkSearchController.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/admin_available.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/admin_available.html
  src/main/resources/templates/main.html
Labels: enhancement

#206 Fix : 예약 차량 요금 표시
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/static/js/admin.js
Labels: fix

#208 Feat: #207 예약차량 입차 버튼 생성
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
Labels: enhancement

#210 feat : #209 관리자페이지 정렬 기능 추가
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/static/js/admin.js
  src/main/resources/templates/admin.html
Labels: enhancement

#211 Fix : 예상 요금및 실제 요금 정산 로직 수정
  src/main/java/com/sparta/parknav/_global/scheduler/SchedulerService.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#213 Fix : 정렬 디폴트를 예약 시작순으로 변경
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/resources/templates/admin.html
Labels: fix

#216 Feat : 관리자페이지 동적쿼리 적용
  src/main/java/com/sparta/parknav/booking/dto/ParkBookingInfoMgtDto.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepositoryCustom.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepositoryImpl.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement
