Repository final-project-teamB/ParkNav2, pull requests merged in 2023-03, with the labels that each got.

#3 CI : CI 뼈대코드 작성
  .github/workflows/gradle.yml
Labels: documentation

#4 Fix : ParkBookingInfo ERD 수정으로 인한 엔티티 변경
  src/main/java/com/sparta/parknav/ticket/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/ticket/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/ticket/repository/TktPrchsInfo.java
Labels: fix

#5 CI : CI / CD 구축
  .github/workflows/gradle.yml
  Dockerfile
  src/main/java/com/sparta/parknav/ParknavApplication.java
Labels: documentation, enhancement

#7 Feat : #6 로그인,회원가입,관리자 페이지 기본 뼈대 코드 구현
  src/main/resources/static/css/login.css
  src/main/resources/static/css/parkMgtInfo.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/js/parkMgtInfo.js
  src/main/resources/templates/login.html
  src/main/resources/templates/parkMgtInfo.html
  src/main/resources/templates/signup.html
Labels: enhancement

#9 Feat : #8 검색 페이지 HTML JS 구현
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement

#11 Feat: #10 json 파일 DB 저장
  src/main/java/com/sparta/parknav/global/data/KakaoMapService.java
  src/main/java/com/sparta/parknav/global/data/MakeData.java
  src/main/java/com/sparta/parknav/global/data/ParkInfoJsonDto.java
  src/main/java/com/sparta/parknav/global/data/ParkOperInfoJsonDto.java
  src/main/java/com/sparta/parknav/parking/entity/ParkInfo.java
  src/main/java/com/sparta/parknav/parking/entity/ParkOperInfo.java
Labels: enhancement

#13 Feat/#12 검색, 현위치 검색 시 대상 위치 주변 주차장 찾는 기능
  src/main/java/com/sparta/parknav/global/data/KakaoMapService.java
  src/main/java/com/sparta/parknav/parking/controller/ParkSearchController.java
  src/main/java/com/sparta/parknav/parking/dto/KakaoSearchDocumentsDto.java
  src/main/java/com/sparta/parknav/parking/dto/KakaoSearchDto.java
  src/main/java/com/sparta/parknav/parking/dto/KakaoSearchMetaDto.java
  src/main/java/com/sparta/parknav/parking/dto/ParkSearchRequestDto.java
  src/main/java/com/sparta/parknav/parking/dto/ParkSearchResponseDto.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
  src/main/resources/static/img/location.png
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement, fix

#14 Fix : CI/CD 확인 완료
  .github/workflows/gradle.yml
Labels: documentation, fix

#17 Feat: #16 회원가입 기능 구현
  src/main/java/com/sparta/parknav/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/global/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/parknav/global/security/UserDetailsImpl.java
  src/main/java/com/sparta/parknav/global/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/parknav/ticket/entity/Car.java
  src/main/java/com/sparta/parknav/ticket/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/user/controller/UserController.java
  src/main/java/com/sparta/parknav/user/dto/LoginRequestDto.java
  src/main/java/com/sparta/parknav/user/dto/LoginResponseDto.java
  src/main/java/com/sparta/parknav/user/dto/SignupRequestDto.java
  src/main/java/com/sparta/parknav/user/entity/Admin.java
  src/main/java/com/sparta/parknav/user/entity/User.java
  src/main/java/com/sparta/parknav/user/repository/UserRepository.java
  src/main/java/com/sparta/parknav/user/service/UserService.java
  src/main/java/com/sparta/parknav/users/repository/UsersRepository.java
Labels: enhancement

#23 Feat : #22 차량 입차 로직 구현
  src/main/java/com/sparta/parknav/ParknavApplication.java
  src/main/java/com/sparta/parknav/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/global/jwt/JwtAuthAdminFilter.java
  src/main/java/com/sparta/parknav/global/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/parknav/global/jwt/JwtUtil.java
  src/main/java/com/sparta/parknav/global/jwt/JwtUtilAdmin.java
  src/main/java/com/sparta/parknav/global/response/MsgType.java
  src/main/java/com/sparta/parknav/parking/entity/ParkInfo.java
  src/main/java/com/sparta/parknav/parking/entity/ParkMgtInfo.java
  src/main/java/com/sparta/parknav/parking/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/ticket/controller/mgtController.java
  src/main/java/com/sparta/parknav/ticket/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/ticket/dto/response/CarInResponseDto.java
  src/main/java/com/sparta/parknav/ticket/dto/response/CarOutResponseDto.java
  src/main/java/com/sparta/parknav/ticket/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/ticket/entity/Car.java
  src/main/java/com/sparta/parknav/ticket/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/ticket/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/ticket/service/mgtService.java
  src/main/java/com/sparta/parknav/user/service/UserService.java
Labels: enhancement

#25 Refactor: #24 management 관련 코드 패키지 변경
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/management/dto/response/CarInResponseDto.java
  src/main/java/com/sparta/parknav/management/dto/response/CarOutResponseDto.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/ticket/entity/Car.java
Labels: refactor

#26 Fix : Jwt 수정
  src/main/java/com/sparta/parknav/global/jwt/JwtAuthFilter.java
  src/main/java/com/sparta/parknav/global/jwt/JwtUtil.java
Labels: fix

#28 Feat: #27 예약 시간 입력 시 정보 조회 기능 구현
  src/main/java/com/sparta/parknav/booking/Service/BookingService.java
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/booking/dto/BookingInfoRequestDto.java
  src/main/java/com/sparta/parknav/booking/dto/BookingInfoResponseDto.java
  src/main/java/com/sparta/parknav/booking/entity/Car.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/booking/repository/CarRepository.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/global/response/MsgType.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/entity/ParkMgtInfo.java
  src/main/java/com/sparta/parknav/parking/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/ticket/repository/ParkBookingInfoRepository.java
Labels: enhancement, refactor

#32 Feat : 출차 로직 구현
  src/main/java/com/sparta/parknav/global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/response/CarInResponseDto.java
  src/main/java/com/sparta/parknav/management/dto/response/CarOutResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/management/service/ParkingFeeCalculator.java
  src/main/java/com/sparta/parknav/parking/entity/ParkMgtInfo.java
  src/main/java/com/sparta/parknav/parking/repository/ParkMgtInfoRepository.java
Labels: enhancement, fix

#34 feat : #33 상세 정보 조회 추가, 주차장정보 수정
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement, refactor

#35 Feat: #29 주차 예약 기능 구현
  src/main/java/com/sparta/parknav/booking/Service/BookingService.java
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/booking/entity/Car.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
  src/main/java/com/sparta/parknav/booking/repository/CarRepository.java
  src/main/java/com/sparta/parknav/global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/global/response/MsgType.java
Labels: enhancement

#38 Feat : #36 주차 현황 조회 API 구현
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#39 Refactor: #27 예약시간 입력 후 정보 조회시, 주차 예상 요금 계산 클래스 사용
  src/main/java/com/sparta/parknav/booking/Service/BookingService.java
  src/main/java/com/sparta/parknav/management/service/ParkingFeeCalculator.java
Labels: refactor

#41 Feat: #30 주차 예약 취소 기능 구현
  src/main/java/com/sparta/parknav/booking/Service/BookingService.java
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/global/response/MsgType.java
Labels: enhancement

#48 feat : 로그인 화면 html
  src/main/resources/templates/login.html
Labels: enhancement

#54 Feat : #52 차량번호 유효성 검사 추가
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#53 Feat : #45 로그인기능 구현
  src/main/resources/templates/main.html
Labels: enhancement

#58 Feat: #29 예약시간을 현재시간 이전으로 선택할 경우 예외처리 삭제
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
Labels: enhancement, refactor

#61 Fix : 입차,출차, 차량등록, 대표차량 등록 로직 수정
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/repository/CarRepository.java
  src/main/java/com/sparta/parknav/management/service/CarRegService.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/repository/ParkMgtInfoRepository.java
Labels: fix

#65 Feat : #64 입차 출차시 입차시간 기준 가장 마지막 데이터만 db에서 가져오기
  src/main/java/com/sparta/parknav/management/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/repository/ParkMgtInfoRepository.java
Labels: enhancement, fix

#68 Feat : #57 마이페이지 틀, 차량등록 기능구현
  src/main/java/com/sparta/parknav/_global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/parking/controller/ParkSearchController.java
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#70 Feat : #69 유저 차량 조회 기능 추가
  src/main/java/com/sparta/parknav/booking/repository/CarRepository.java
  src/main/java/com/sparta/parknav/management/controller/CarRegController.java
  src/main/java/com/sparta/parknav/management/dto/response/CarListResponseDto.java
  src/main/java/com/sparta/parknav/management/service/CarRegService.java
Labels: enhancement

#72 Feat: #63 나의 예약 현황 조회 기능 구현
  src/main/java/com/sparta/parknav/_global/response/MsgType.java
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/booking/dto/MyBookingResponseDto.java
  src/main/java/com/sparta/parknav/booking/entity/StatusType.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
Labels: enhancement

#75 Feat : #74 나의 차량 삭제
  src/main/java/com/sparta/parknav/_global/response/MsgType.java
  src/main/java/com/sparta/parknav/booking/repository/CarRepository.java
  src/main/java/com/sparta/parknav/management/controller/CarRegController.java
  src/main/java/com/sparta/parknav/management/dto/request/CarNumDeleteRequestDto.java
  src/main/java/com/sparta/parknav/management/service/CarRegService.java
  src/main/resources/templates/main.html
Labels: enhancement

#77 Feat/#76 프론트 토큰 만료 처리
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
Labels: enhancement

#80 Chore: #63 나의 예약 현황 조회시 주차장 ID 포함하여 리턴
  src/main/java/com/sparta/parknav/booking/dto/MyBookingResponseDto.java
Labels: refactor

#79 Feat : #78 마이페이지 기능구현(차량관리)
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/mypage.html
Labels: enhancement

#81 Chore: #63 나의 예약 현황 조회시 예약정보ID 포함하여 리턴
  src/main/java/com/sparta/parknav/booking/dto/MyBookingResponseDto.java
Labels: refactor

#73 Feat: #71 주차 현황 조회 Page 구현
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/CarRegService.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: enhancement

#86 Fix : #85 totalpages 갯수 오류 수정
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#84 Feat : #83 프론트 주차장 운영시간 외 수정
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/main.html
Labels: enhancement

#89 Chore : 기존 5번 시나리오를 앞쪽으로 배치
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/dto/request/CarNumRequestDto.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#91 Feat : #90 프론트 관리자, 마이페이지 페이징 구현
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/mypage.js
  src/main/resources/templates/admin.html
  src/main/resources/templates/main.html
  src/main/resources/templates/mypage.html
Labels: enhancement

#93 Fix : #92 검색 시 available 삭제
  src/main/resources/static/js/main.js
Labels: fix

#95 Fix : #94 위치 검색기능 상세 조건 추가
  src/main/java/com/sparta/parknav/parking/controller/ParkSearchController.java
  src/main/java/com/sparta/parknav/parking/dto/ParkOperInfoDto.java
  src/main/java/com/sparta/parknav/parking/dto/ParkSearchResponseDto.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
  src/main/resources/static/img/clocation.png
  src/main/resources/static/js/main.js
Labels: enhancement

#97 Fix: #96 예약시간 입력시 정보 조회 수정
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/parking/repository/ParkOperInfoRepository.java
Labels: fix

#99 Fix : #98 프론트 회원가입 기능 추가
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement

#101 Fix : #100 관리자 페이지 일반토큰 삭제 문제
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
Labels: fix

#103 Feat: #102 주차장 정보, 예약정보 데이터 생성 코드 작성
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
  src/main/java/com/sparta/parknav/_global/data/ParkInfoJsonDto.java
  src/main/java/com/sparta/parknav/booking/entity/ParkBookingInfo.java
Labels: enhancement

#104 Refactor : 데이터 생성 메서드 포스트맨 작동 수정
  src/main/java/com/sparta/parknav/_global/config/WebSecurityConfig.java
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
  src/main/java/com/sparta/parknav/_global/data/MakeDataController.java
Labels: enhancement, fix

#105 Fix : #100 주차장관리정보 데이터 생성
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
  src/main/java/com/sparta/parknav/_global/data/MakeDataController.java
Labels: refactor

#106 Feat: #102 주차 현황정보 데이터 생성
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
  src/main/java/com/sparta/parknav/_global/data/MakeDataController.java
  src/main/java/com/sparta/parknav/_global/response/MsgType.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/repository/ParkOperInfoRepository.java
  src/main/java/com/sparta/parknav/user/repository/UserRepository.java
Labels: enhancement, refactor

#107 Chore : 주차장 관리자 페이지에서 주차장 이름 응답에 추가
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtListResponseDto.java
  src/main/java/com/sparta/parknav/management/dto/response/ParkMgtResponseDto.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#109 CI : 도커 이미지 및 컨테이너 자동 삭제 보완
  .github/workflows/gradle.yml
Labels: bug, fix

#108 Chore: #102 데이터 100건 저장시 flush 처리
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
Labels: fix

#112 Fix : 차량이 입차시 예약차량 숫자 로직 수정
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix

#111 Fix: #102 예약차량 입차한 현황 데이터 생성시 예외처리
  src/main/java/com/sparta/parknav/_global/data/MakeData.java
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
Labels: fix

#115 Feat : 관리자페이지 주차장명 표기
  src/main/resources/static/js/admin.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/admin.html
Labels: enhancement

#116 Fix: #110 예약시간 입력시 정보조회 수정사항 반영
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
Labels: fix

#118 refactor : #117 검색 시 Object로 반환받던 부분 변경
  src/main/java/com/sparta/parknav/parking/dto/ParkOperInfoDto.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: refactor

#120 Feat : #119 Redis 뼈대 구현
  build.gradle
  src/main/java/com/sparta/parknav/_global/exception/ErrorType.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/redis/RedisConfig.java
  src/main/java/com/sparta/parknav/redis/RedisLockRepository.java
Labels: enhancement

#122 Refactor : #121 ApiResponseDto 서비스로직에서 삭제 및 컨트롤러에 추가
  src/main/java/com/sparta/parknav/booking/controller/BookingController.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/controller/MgtController.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
  src/main/java/com/sparta/parknav/parking/controller/ParkSearchController.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
  src/main/java/com/sparta/parknav/user/controller/UserController.java
  src/main/java/com/sparta/parknav/user/service/UserService.java
Labels: refactor

#126 CI : #125 Chat GPT 코드리뷰 기능 테스트 PR
  .github/workflows/gradle.yml
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
Labels: documentation, enhancement

#129 feat : #128 주차장 검색 검색결과 유사도 판별 기능 적용
  build.gradle
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: enhancement

#131 Fix: #130 기존 예약, 입차 알고리즘 수정사항 적용
  src/main/java/com/sparta/parknav/booking/repository/ParkBookingInfoRepository.java
  src/main/java/com/sparta/parknav/booking/service/BookingService.java
  src/main/java/com/sparta/parknav/management/repository/ParkMgtInfoRepository.java
  src/main/java/com/sparta/parknav/management/service/MgtService.java
Labels: fix, refactor

#136 refactor : #135 주차가능대수 추가 ,주변검색 거리 변경
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
  src/main/resources/static/img/location.png
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: refactor

#134 Fix: #132 현재 주차 가능대수 출력 부분 수정
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: fix

#138 Feat : #137 실행시간 측정 aop 뼈대 구현
  src/main/java/com/sparta/parknav/_global/annotation/NoChecking.java
  src/main/java/com/sparta/parknav/_global/aop/TimeChecking.java
Labels: enhancement

#142 feat : #140 프론트 지도 클러스터 생성
  src/main/java/com/sparta/parknav/parking/entity/ParkType.java
  src/main/resources/static/img/location.png
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: enhancement

#141 feat : #139 주차장 검색에 QueryDSL 동적쿼리 적용
  .gitignore
  build.gradle
  src/main/java/com/sparta/parknav/_global/config/QuerydslConfiguration.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepository.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepositoryCustom.java
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepositoryImpl.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: enhancement

#144 feat : #143 주차장 검색 성능개선
  src/main/java/com/sparta/parknav/parking/repository/ParkInfoRepositoryImpl.java
  src/main/java/com/sparta/parknav/parking/service/ParkSearchService.java
Labels: refactor

#148 feat : #147 프론트 주차장 클릭 시 정보 가져오기
  src/main/resources/static/js/main.js
Labels: enhancement
